### PR TITLE
Fix `cc` & `bcc` with Quartz::Composer

### PR DESCRIPTION
**Pull request by westonganger**
Also solves #23

### CODE REVIEW

**Review by robacarp — APPROVED** [review]
Thanks @westonganger. This looks right, but there's no composer test to update to validate. I've created #23 for that, unless you want to contribute one *wink*

**Comment by westonganger** [comment]
Sure. I have now added a spec for `Quartz::Composer`

**Review by drujensen — APPROVED** [review]

**Comment by drujensen** [comment]
thanks for the test coverage!

**Comment by robacarp** [comment]
@westonganger awesome! Thank you so much!

**Pull request merged**
