### PR TITLE
Improve Instructions for `to` API

### PR DESCRIPTION
**Pull request by westonganger**

### CODE REVIEW

**Review by robacarp — APPROVED** [review]
this is great. Do you think it would benefit the readme to have a multiple-recipient example too?

**Comment by westonganger** [comment]
Probably. I usually prefer to pass the recipients in as an array, an example for that would be great.

**Comment by westonganger** [comment]
Ok I have now added a multiple recipient example.

**Review by drujensen — APPROVED** [review]

**Comment by robacarp** [comment]
@westonganger thank you!

**Pull request merged**
